apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::533267192490:role/eksctl-basic-cluster-nodegroup-bas-NodeInstanceRole-orhba8viySe0
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:    
      - pod-reader 
      userarn: arn:aws:iam::533267192490:user/Rohit
      username: Rohit

kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-05T12:06:34Z"
  name: aws-auth
  namespace: kube-system
  uid: b68e919a-71a0-4853-a7d6-349a2c84a0ec
